sudo: false
language: java
jdk:
  - oraclejdk8
before_deploy:
  - rm -f target/original-*.jar
  - export RELEASE_PKG_FILE=$(ls target/*.jar)
  - echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: HZm3+bM1ByNZdPZ2vWo2eBpP/GiQ6bJEyE0vUL/gmyl18hkI0fVbx4YLXntBI/AagC5E5M6y/3qeNajSw5h9+nMciXfjQy50UIkb7uXwEnOoNQl2eYfQ2qnCWKUTJlRs5gsJI/KF4eB7u/Xgu/vSHWAJS+Gzr8AuZeU2ct9nmxA2ntWDjnJwUv9/weJsG6oMfxl+FwW67ctQyh8rGa12Pby2KRdrUoDgSAYe7AH+GCgzzATLzAJfV9wbbKc+xE0ST8wkiSA21tZfbc8ifHPIsvjoWqKjGSrxljnPevtYzO/A3nUHPLXayoMZFlgtm1axavqc6y2JgKjOc5R2v0YFkBOFkHva/sVjLnxjTNlL3lw5HIIgwjhLikYrTquy4wtPi7bmezYGrJMsVJ50yfxVP/8YAx1ULWiV7VZiBIeoP/vNcTjm7yqvPMINma1kH2+Lssk9jmUKZelVWD2RoWTpA4MSLUlXriSouzggUNKGCIYQp9aJ0pbFbBSo49MaoLSaSSM3Yw8tPv8F4dAoXryrvzTopB9UzN+Va2EsNig0bduciDj1ZFwSNJGcE4nxt5QHN6bEmhOPYu3ZYfIOSzAu9AXBTmX4/qEZ9L8FPILaGcQK5ht9eqjBw1KFOixUVIgKI2/eQ1M3I6ndLSBMmi3MnHQ/9IQls6G3BCQrXb74fdw=
  file: 
    - "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8

